// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  blogs: dynamic(() => import("./Blogs")),
  introduction: dynamic(() => import("./Introduction")),
  projects: dynamic(() => import("./Projects")),
};
