import './globals.css';
import type { Metadata } from 'next';
import { Nunito_Sans, Instrument_Sans } from 'next/font/google';
import { cn } from '@/utils/cn';

const nunito = Nunito_Sans({ subsets: ['latin'], variable: '--font-nunito' });
const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  variable: '--font-instrument',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          (cn(nunito.variable, instrumentSans.variable), 'font-default')
        }
      >
        {children}
      </body>
    </html>
  );
}
